### PR TITLE
Added private $_postErrors = array();

### PR DESCRIPTION
**Pull request by sagarishere**
This was missing from the module.

### CODE REVIEW

**Comment by tpeigne** [comment]
Hello sagaradonis !

I can't find any use case of this variable in the Prestashop code. Can you give me an example of when this variable is used ?

Thanks,
tpeigne

**Comment by sagarishere** [comment]
I am not an expert and a newbie. I will try to find the answer and write within 24 hours.

**Comment by sagarishere** [comment]
Okay - it throws errors that happen during execution of php code either in prestashop or your own module. This is different from displayerror () function.

This throws errors into errors but does not display them - so this can be used to capture errors and either display them or catch them and put conditions on them to act in different ways. For example - instead of 404 you may want to display a dynamic search..

**Comment by tpeigne** [comment]
Ok, thanks !

Another question, where did you find the part of Prestashop code which use the $_postErrors variable ?

Thanks,
tpeigne

**Comment by sagarishere** [comment]
I also could not find anywhere $_postErrors being used.

**Comment by sagarishere** [comment]
Can you help me with a small thing. I am using simpleresponsivetheme at my website www.dailydeliver.com and I am trying to add an "Add to Cart" button in ResponsiveHomeFeatured.

Now I have added this code in responsivehomefeatured.tpl 
res

And this does not pickup the product id. Whenever I add to cart - it gives me an error. Can you as an expert tell where I am making the mistake ?

**Comment by sagarishere** [comment]
I have made a bit of progress and am able to get the product link via $link->getProductLink

but still it is showing errors.

Do tell me if you are able to find a solution.

My current code runs like this:

respo

**Comment by sagarishere** [comment]
IT SHOWS ME THE ERROR:

"The product is no longer available"

**Comment by tpeigne** [comment]
Hello,

Please open only one subject per issue.

If you want help concerning theme customization, please ask the community in this post : http://www.prestashop.com/forums/topic/244041-free-simple-responsive-theme-15x/

I close this issue until we find a use for this variable in the Prestashop code.

Thanks,
tpeigne

**Pull request closed without merging**
